import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const api = 'http://localhost:8000/api';
const stages=['Repository Analyzer','Retriever','Planner','Implementation','Testing','Security','Review'];
const requestHeaders=token=>({'Content-Type':'application/json',Authorization:`Bearer ${token}`});

function Landing({onStart}) {
  return <main className="landing"><nav><div className="brand"><span className="mark">◈</span><b>AI SWE <em>COMMAND</em></b></div><button className="ghost" onClick={onStart}>SIGN IN</button></nav><section className="landing-hero"><p className="eyebrow">AUTONOMOUS ENGINEERING OPERATIONS</p><h1>Ship with clarity.<br/><span>Operate with confidence.</span></h1><p>One command center for planning, code changes, validation, security checks, and a complete audit trail.</p><div><button onClick={onStart}>ENTER COMMAND CENTER <span>→</span></button><button className="ghost" onClick={onStart}>VIEW THE FLOW</button></div></section><section className="feature-row"><article><i>01</i><h3>MISSION CONTROL</h3><p>Turn a plain-English request into an observable engineering run.</p></article><article><i>02</i><h3>SAFE EXECUTION</h3><p>Every code edit, command, and test result is recorded for review.</p></article><article><i>03</i><h3>FULL TELEMETRY</h3><p>See the plan, pipeline, diffs, security signals, and final verdict.</p></article></section></main>
}

function Login({onLogin,onBack}) {
  const [email,setEmail]=useState('admin@example.com'); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${api}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Unable to authenticate');onLogin(data.access_token,data.user)}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="auth"><button className="back" onClick={onBack}>← BACK</button><section className="auth-card"><div className="brand"><span className="mark">◈</span><b>AI SWE <em>COMMAND</em></b></div><p className="eyebrow">SECURE ACCESS GATEWAY</p><h1>Operator sign in</h1><p className="muted">Use the administrator credentials configured in your environment.</p><form onSubmit={submit}><label>EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/></label><button disabled={busy}>{busy?'AUTHENTICATING…':'AUTHENTICATE →'}</button></form>{error&&<p className="error">{error}</p>}<small>Default local email: admin@example.com</small></section></main>
}

function Dashboard({token,user,onLogout}) {
  const [repo,setRepo]=useState(''); const [request,setRequest]=useState('Add a health-check endpoint to this FastAPI application.'); const [run,setRun]=useState(null); const [error,setError]=useState('');
  async function start(){try{setError('');const p=await fetch(`${api}/projects`,{method:'POST',headers:requestHeaders(token),body:JSON.stringify({repository_url:repo})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail);return d});const t=await fetch(`${api}/tasks`,{method:'POST',headers:requestHeaders(token),body:JSON.stringify({project_id:p.id,request})}).then(r=>r.json());await fetch(`${api}/tasks/${t.id}/run`,{method:'POST',headers:requestHeaders(token)});const get=x=>fetch(`${api}/tasks/${t.id}${x}`,{headers:requestHeaders(token)}).then(r=>r.json());const [task,logs,changes,tests,review]=await Promise.all(['','/logs','/changes','/tests','/review'].map(get));setRun({task,logs,changes,tests,review})}catch(e){setError(e.message)}}
  return <main><header><div className="brand"><span className="mark">◈</span><div><p className="eyebrow">SYSTEM ONLINE · V0.1</p><h1>AI SWE <em>COMMAND</em></h1></div></div><div className="operator"><span><i/> {user.email}</span><button className="ghost" onClick={onLogout}>LOG OUT</button></div></header><section className="hero"><div><p className="eyebrow">AUTONOMOUS ENGINEERING CONSOLE</p><h2>Deploy changes with<br/><span>full mission telemetry.</span></h2><p className="muted">Plan, patch, validate, and review software changes—without losing the audit trail.</p></div><div className="radar"><span>AGENT</span><b>READY</b></div></section><section className="card launch"><div className="card-title"><span>01</span><h3>Initialize mission</h3></div><div className="fields"><label>REPOSITORY TARGET<input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/org/repository"/></label><label>ENGINEERING OBJECTIVE<textarea value={request} onChange={e=>setRequest(e.target.value)}/></label></div><button onClick={start} disabled={!repo}><span>▶</span> LAUNCH AGENT</button>{error&&<p className="error">{error}</p>}</section><section className="card pipeline"><div className="card-title"><span>02</span><h3>Agent pipeline</h3>{run&&<b className="status">{run.task.status}</b>}</div><div className="stages">{stages.map((stage,i)=>{const log=run?.logs.find(x=>x.agent.toLowerCase().replaceAll(' ','-')===stage.toLowerCase().replaceAll(' ','-'));return <div className={log?'stage done':'stage'} key={stage}><strong>{String(i+1).padStart(2,'0')}</strong><i>{log?'✓':'○'}</i><span>{stage}</span></div>})}</div></section>{run&&<><section className="card mission"><div className="card-title"><span>03</span><h3>Mission report</h3></div><h2>{run.task.plan?.summary}</h2><div className="logbox">{run.logs.map((l,i)=><p key={i}><b>[{l.agent.toUpperCase()}]</b> {l.message}</p>)}</div></section><section className="grid"><article className="card"><div className="card-title"><span>04</span><h3>Change set</h3></div>{run.changes.map(c=><details key={c.path}><summary><b>MODIFIED</b> {c.path}</summary><p>{c.reason}</p><pre>{c.modified}</pre></details>)}</article><article className="card"><div className="card-title"><span>05</span><h3>Validation</h3></div>{run.tests.map((t,i)=><pre key={i}><b className={t.status}>{t.status.toUpperCase()}</b> · {t.command}\n{t.stdout||t.stderr}</pre>)}<div className="verdict"><p>CODE REVIEW</p><h2>{run.review.review?.verdict}</h2><span>{run.review.review?.summary}</span></div></article></section></>}</main>
}

function App(){const [view,setView]=useState(sessionStorage.getItem('token')?'dashboard':'landing');const [token,setToken]=useState(sessionStorage.getItem('token')||'');const [user,setUser]=useState(JSON.parse(sessionStorage.getItem('user')||'null'));function login(t,u){sessionStorage.setItem('token',t);sessionStorage.setItem('user',JSON.stringify(u));setToken(t);setUser(u);setView('dashboard')}function logout(){sessionStorage.clear();setToken('');setUser(null);setView('landing')}return view==='landing'?<Landing onStart={()=>setView('login')}/>:view==='login'?<Login onLogin={login} onBack={()=>setView('landing')}/>:<Dashboard token={token} user={user} onLogout={logout}/>}
createRoot(document.getElementById('root')).render(<App/>);
