import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const api = 'http://localhost:8000/api';
function App() {
  const [repo,setRepo]=useState(''); const [request,setRequest]=useState('Add a health-check endpoint to this FastAPI application.'); const [run,setRun]=useState(null); const [error,setError]=useState('');
  async function start() { try { setError(''); const p=await fetch(`${api}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:repo})}).then(r=>r.json()); const t=await fetch(`${api}/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:p.id,request})}).then(r=>r.json()); await fetch(`${api}/tasks/${t.id}/run`,{method:'POST'}); const [task,logs,changes,tests,review]=await Promise.all(['','/logs','/changes','/tests','/review'].map(x=>fetch(`${api}/tasks/${t.id}${x}`).then(r=>r.json()))); setRun({task,logs,changes,tests,review}); } catch(e) {setError(e.message)} }
  return <main><header><span className="mark">⌘</span><div><h1>AI SWE Agent</h1><p>Autonomous, auditable engineering runs</p></div></header><section className="card"><label>GitHub repository or local repository path<input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/org/repository"/></label><label>Engineering task<textarea value={request} onChange={e=>setRequest(e.target.value)}/></label><button onClick={start} disabled={!repo}>Run agent</button>{error&&<p className="error">{error}</p>}</section>{run&&<><section className="card"><h2>{run.task.status}</h2><p>{run.task.plan?.summary}</p><h3>Pipeline</h3><ol>{run.logs.map((l,i)=><li key={i}><b>{l.agent}</b> — {l.message}</li>)}</ol></section><section className="grid"><article className="card"><h2>Changes</h2>{run.changes.map(c=><details key={c.path}><summary>{c.path}</summary><p>{c.reason}</p><pre>{c.modified}</pre></details>)}</article><article className="card"><h2>Tests</h2>{run.tests.map((t,i)=><pre key={i}>{t.status} · {t.command}\n{t.stdout||t.stderr}</pre>)}<h2>Review</h2><p>{run.review.review?.verdict}</p><p>{run.review.review?.summary}</p></article></section></>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
